describe('test Suite', () => {
    it('first test', () => {
cy.visit('https://sat.propertyware.com/pw/login.jsp')
cy.get('input[id=loginEmail]').type('sam@texasrenters.com')
        cy.get('input[type=password]').type('Realpage!12')
        cy.get('input[value="Sign Me In"]').click()
        cy.get('a[href^="/pw/maintenance/maintenance_home.do"]').click()
        cy.get('[id=tab2]').click()
        cy.get('input[value="New Service Agreement"]').click()
        cy.get("input[name='entity.contractNumber']").type('73851653')
        cy.get("input[value='Choose Contact']").click()
        cy.get('input[id="contactSearchText"]').type('test')
        cy.get('input[value="Search"]').click()       
        cy.get('tr:nth-child(2) > td:nth-child(1) > input[type=radio]').click()
        cy.get('input[value="Done"]').click()
        cy.get('input[name="sendTenantAlert"]').click()
        cy.get('input[name="entity.hourEstimate"]').clear().type('3')
        cy.get('input[name="entity.costEstimateAsString"]').clear().type('100.00')
        cy.get('[name="entity.specificLocation"]').type('test')
        cy.get('input[name="entity.recurrence.startDateAsString"]').type('03/03/2021')
        cy.get('input[value="Attach Assets"]').click()
        cy.get('input[name="searchText"]').type('*')
        cy.get('input[value="Search"]').click()
        cy.get('tr:nth-child(2) > td:nth-child(1) > input[type=checkbox]').click()
        cy.get(' input[value="Done"]').click()
        cy.get('input[value="Attach Vendor"]').click()
        cy.get('input[id="vendorSearchText"]').type('*')
        cy.get('input[value="Search"]').click()
        cy.get('tr:nth-child(2) > td:nth-child(1) > input[type=checkbox]').click()
        cy.get(' input[value="Done"]').click()
        cy.get('input[name="entity.recurrence.interval"]').type('3')
        cy.get("li:nth-child(1) > input[type='checkbox']").click()
        cy.get("li:nth-child(4) > input[type='checkbox']").click()
        cy.get("li:nth-child(3) > input[type='checkbox']").click()
        cy.get("div.primaryButtons:nth-child(14) > input:nth-child(1)").click()
        cy.get("input[value='Delete']").click()
     
})
})